# Generated by Django 4.2.5 on 2024-04-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPBase",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("ltl", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RQComponent",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RQCondition",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RQTemplate",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("content1", models.CharField(blank=True, max_length=255, null=True)),
                ("content2", models.CharField(blank=True, max_length=255, null=True)),
                ("content3", models.CharField(blank=True, max_length=255, null=True)),
                ("content4", models.CharField(blank=True, max_length=255, null=True)),
                ("content5", models.CharField(blank=True, max_length=255, null=True)),
                ("content6", models.CharField(blank=True, max_length=255, null=True)),
                ("content7", models.CharField(blank=True, max_length=255, null=True)),
                ("content8", models.CharField(blank=True, max_length=255, null=True)),
                ("content9", models.CharField(blank=True, max_length=255, null=True)),
                ("content10", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RQWorkMode",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="IPRequirement",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(max_length=255)),
                ("requirement", models.CharField(max_length=255)),
                (
                    "ip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.ipbase"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.rqtemplate",
                    ),
                ),
            ],
        ),
    ]
