# Generated by Django 4.2.5 on 2024-04-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "blog",
            "0002_ipbase_rqcomponent_rqcondition_rqtemplate_rqworkmode_and_more_3",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipbase",
            name="ltl",
        ),
        migrations.AddField(
            model_name="rqtemplate",
            name="ltl",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
