# Generated by Django 4.2.5 on 2024-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_ipbase_ltl_rqtemplate_ltl"),
    ]

    operations = [
        migrations.CreateModel(
            name="RQWordSub",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("engname", models.CharField(max_length=255)),
                ("chname", models.CharField(max_length=255)),
            ],
        ),
    ]
